# Plugins
gems:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']


# Site Settings
title: "MathDay 2024 Vaasa"
email: ""
description: "An event to share and promote the beauty of maths in engineering."
baseurl: "/mathday2024"
url: "https://lucaferranti.com/mathday2024"
permalink: "/blog/:title"
googleAnalyticsTrackingId: ""
googleAnalyticsSiteUrl: ""
siteVerification: ""

# Organizer Info
organizerName: "Mohammed Elmusrati and Luca Ferranti"
organizerAlternateName: "Mohammed and Luca"
organizerDescription: ""
organizerEmail: "mohammed.elmusrati@uwasa.fi"
organizerLogo: "/img/seo/organizer-logo.png"
organizerLink: "http://uwasa.fi"

# Head
metaKeywords: "maths, open science, education, STEM"
twitterAccount: ""
socialImageSrcGooglePlus: ""
socialImageSrcTwitter: ""
socialImageSrcFacebook: ""


# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
 - {permalink: "/#about", text: "About"}
 - {permalink: "/#guest", text: "Speakers"}
 - {permalink: "/#schedule", text: "Schedule"}
# - {permalink: "/#logistics", text: "Logistics"}
bottomNavigationLinks:
 - {link: "https://forms.gle/6mWUY5tevPTFfRtb6", text: "Register"}
rightNavigationButtons:
 - {link: "https://forms.gle/6mWUY5tevPTFfRtb6", text: "Register"}

# Hero Block
heroImage: "hero.jpg"
heroTitle: "MathDay2024 <typeout>"
eventDate: "April 25th, 2024"
typeoutTextValues: '"", "April 25th", "University of Vaasa", "Finland"'
typeoutFallback: "Season"
heroButtons:
 - {link: "https://forms.gle/6mWUY5tevPTFfRtb6", text: "Register now!"}
# - {permalink: "/#tickets", text: "Buy tickets"}

# About Block
aboutTitle: "About MathDay2024"
aboutBlock:
 - {title: "Conference", image: "conference.jpg", text: "The biggest Google related event in the country carefully crafted for you by GDG community! Awesome speakers and lots of fun!" }
 - {title: "Workshops", image: "workshop.jpg", text: "Full-day of workshops, hands-on experience, hacking and debugging. Come and tame your favourite technology!" }
 - {title: "Hackathon", image: "hackathon.jpg", text: "Full-day freestyle hackathon! Want some real team building on friday? Grab your team and join our hackathon!" }

# Guests block
guestTitle: "Unconference talks"
guestBlock:
 - {title: "Tommi<br>Sottinen", image: "sottinen.jpg", text: ""}
 - {title: "Luca<br>Ferranti", image: "ferranti.jpg", text: ""}
 - {title: "Bernd<br>Pape", image: "pape.jpg", text: ""}

# Latest News Block
latestNewsTitle: "Latest news"

# Location Block
locationBlockTitle: "Location"
eventLocationName: "University of Vaasa"
eventLocationLink: "http://uwasa.fi/"
eventStreetAddress: "Wolffintie 32"
eventAddressLocality: "Vaasa"
eventAddressLocalityRegion: "Pohjanmaa"
eventPostalCode: "65200"
eventAddressCountry: "Finland"
eventStartTime: "2024-04-25T10:00"
eventDoorTime: "09:00"
eventEndTime: "2024-04-25T17:00"
eventPlaceCoordinates: "63.10552, 21.59286"
mapCenterCoordinates: "63.10552, 21.59286"
mapMobileCenterCoordinates: "63.10552, 21.59286"

# Venue Block
venueBlockTitle: "Venue"
venueBigImage: "venue_0.jpg"
venueSmallImage1: "venue_1.jpg"
venueSmallImage2: "venue_2.jpg"
venueSmallImage3: "venue_3.jpg"
venueTitle: "University of Vaasa"
venueFeatures: ["arcade videogames", "seaview", "Most beautiful campus in Finland"]

# Tickets Block
ticketsTitle: "Pricetable"
ticketsInfo: "Tickets grant access to all conference sections, coffee brakes, lunch and party. Accommodation is NOT included in the ticket price."
ticketsOffers:
 -
  name: "Early Bird"
  price: "350"
  priceCurrency: "UAH"
  ticketsNumber: "150"
  ribbon: "-5%"
  buyButtonLink: "http://dfua.ticketforevent.com/"
  buyButtonText: "Buy Now"
  ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
  validFrom: "2014-08-25T10:00"
  validThrough: "2014-09-30T23:59"
 -
  name: "Last Chance"
  price: "450"
  priceCurrency: "UAH"
  ticketsNumber: "100"
  ribbon: "-20%"
  featured: true
  buyButtonLink: "http://dfua.ticketforevent.com/"
  buyButtonText: "Buy Now"
  ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
  validFrom: "2014-10-01T00:00"
  validThrough: "2014-10-23T23:59"
  disabled: true
 -
  name: "Student"
  price: "200"
  priceCurrency: "UAH"
  ticketsNumber: "50"
  buyButtonLink: "http://dfua.ticketforevent.com/"
  buyButtonText: "Buy Now"
  additionalInfo: "Requires a valid student ID at the conference check in. Without student ID at the check in, ticket will be cancelled without refund"
  ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
  validFrom: "2014-08-20T10:00"
  validThrough: "2014-10-23T23:59"
  soldOut: true
  soldOutText: "Sold Out"

# Footer
socialLinks:
footerBlocks:
 -
  title: "Contacts"
  links:
   - {link: "mailto:mohammed.elmusrati@uwasa.fi", text: "mohammed.elmusrati@uwasa.fi"}
   - {link: "mailto:luca.ferranti@uwasa.fi", text: "luca.ferranti@uwasa.fi"}
 -
  title: "FAQ"
  links:
   - {permalink: "/cod/", text: "Code of Conduct"}

# Blog
blogTitle: "Latest news"
blogCommentsEnabled: true
discusShortName: "devfestua"

# Speakers List Block
showSessions: true

